# -*- coding: utf-8 -*-
"""air-quality-etl-pipeline

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ovgLEbbN4VM-YkE1JERCTkkCg8BOPEDL
"""

import requests

url = "https://air-quality-api.open-meteo.com/v1/air-quality?latitude=-33.92&longitude=18.42&hourly=pm10,pm2_5,carbon_monoxide,nitrogen_dioxide&timezone=auto"

print("Fetching air quality data from the server...")
response = requests.get(url)

if response.status_code == 200:
    print("Success! Data acquired. 🚀")
    raw_data = response.json()
    print("\nHere is what the API handed back to us:")
    print(raw_data.keys())
else:
    print(f"Failed to fetch data. Error code: {response.status_code}")

import pandas as pd

hourly_data = raw_data['hourly']

df = pd.DataFrame(hourly_data)

df['time'] = pd.to_datetime(df['time'])

df.head()

import sqlite3
conn = sqlite3.connect('health_data.db')

print("Database connection established. 🔌")

df.to_sql('cape_town_air_quality', conn, if_exists='replace', index=False)

print("Data successfully loaded into the SQL table! 💾")

query = """
SELECT time, carbon_monoxide, pm10, pm2_5
FROM cape_town_air_quality
ORDER BY carbon_monoxide DESC
LIMIT 5;
"""

top_pollution = pd.read_sql(query, conn)
print("\n--- Top 5 Highest Carbon Monoxide Readings in Cape Town ---")
print(top_pollution)

conn.close()

!pip install schedule

import schedule
import time
import requests
import pandas as pd
import sqlite3
from datetime import datetime

def run_air_quality_etl():
    print(f"\n--- 🚀 Starting ETL Pipeline at {datetime.now().strftime('%Y-%m-%d %H:%M:%S')} ---")

    url = "https://air-quality-api.open-meteo.com/v1/air-quality?latitude=-33.92&longitude=18.42&hourly=pm10,pm2_5,carbon_monoxide&timezone=auto"
    response = requests.get(url)

    if response.status_code == 200:
        raw_data = response.json()

        df = pd.DataFrame(raw_data['hourly'])
        df['time'] = pd.to_datetime(df['time'])

        conn = sqlite3.connect('health_data.db')
        df.to_sql('cape_town_air_quality', conn, if_exists='append', index=False)
        conn.close()

        print("✅ Success: Data extracted, cleaned, and loaded into the database.")
    else:
        print(f"❌ Error: Could not connect to API. Status code: {response.status_code}")

schedule.every().day.at("06:00").do(run_air_quality_etl)

print("Pipeline automated! Waiting for the next scheduled run...")

while True:
    schedule.run_pending()
    time.sleep(60)